# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Android flavor

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: JSON to variables
        uses: antifree/json-to-variables@v1.1.1
        with:
          filename: 'configs/version.json'
          prefix: 'build'
      - name: Show output
        run: echo "The time was ${{ env.VersionName }}, ${{ env.VersionCode }}, = ${{github.run_number}}"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - name: Install dependencies
        run: flutter pub get

      # Setup Ruby, Bundler, and Gemfile dependencies
  #    - name: Setup Fastlane
  #      uses: ruby/setup-ruby@54a18e26dbbb1eabc604f317ade9a5788dddef81 # v1.159.0
  #      with:
  #        ruby-version: "2.6"
  #        bundler-cache: true
  #        working-directory: android

      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.SIGNING_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        working-directory: android

      - name: Create Google Play Config file
        run : |
          echo "$PLAY_CONFIG_JSON" > play_config.json.b64
          base64 -d -i play_config.json.b64 > play_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}

      - run: flutter build apk --flavor dev --build-name ${{ env.VersionName }} --build-number ${{ env.VersionCode }}  
#
  #    - name: Sign App Bundle
  #      uses: r0adkll/sign-android-release@v1
  #      id: sign_app
  #      with:
  #       releaseDirectory: build/app/outputs/bundle/devRelease
  #       signingKeyBase64: ${{ secrets.SIGNING_KEY }}
  #       alias: ${{ secrets.ALIAS }}
  #       keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
  #       keyPassword: ${{ secrets.KEY_PASSWORD }}
      
      - name: Upload Signed App Bundle
        uses: actions/upload-artifact@v3
        with:
          name: signed-apk
          path: build/app/outputs/flutter-apk/app-dev-release.apk
  #    - name: Upload to Play Store (Internal Testing)
 #       uses: r0adkll/upload-google-play@v1.1.2
 #       with:
  #        #serviceAccountJsonPlainText: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
  #        serviceAccountJson: play_config.json
   #       packageName: com.tung.first_app.dev
   #       releaseFiles: build/app/outputs/bundle/devRelease/app-dev-release.aab       
   #       mappingFile: ./build/app/outputs/mapping/devRelease/mapping.txt
   #       track: internal
   #       changesNotSentForReview: true

          #status: draft
    #  - run: bundle exec fastlane beta
    #    env:
    #      PLAY_STORE_CONFIG_JSON: ${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}
    #    working-directory: android
