name: Review Android Development

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1.6.0

      - uses: invertase/github-action-dart-analyzer@v2.0.0
