name: Review Android Development

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.2'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

     # - uses: dart-lang/setup-dart@v1.6.0

      - uses: invertase/github-action-dart-analyzer@v2.0.0
        with:
          # (Optional) Treat info level issues as fatal.
          fatal-infos: false

          # (Optional) Treat warning level issues as fatal
          # (defaults to true).
          fatal-warnings: false
