name: Review Android Development

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: invertase/github-action-dart-analyzer@v1
